### ISSUE TITLE
Pubish to OpenVSX

### ISSUE THREAD

**Issue by kalebpace** [inci-august/august-themes#5]
Hey, thanks for making this extension!

I recently made the jump to using VS Codium and it does not have access to the Microsoft marketplace by default. Would you be interested in publishing the extension to OpenVSX as well? 

How to:
https://github.com/eclipse/openvsx/wiki/Publishing-Extensions#how-to-publish-an-extension

Thanks for your time :blush:

**Comment by inci-august** [comment]
Published to OpenVSX.
